name: Release

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Run Tests
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: 'pnpm i && pnpm lint'
